### PR TITLE
Release 1.1.16

### PR DESCRIPTION
**Pull request by martinRenou**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martinRenou** [comment]
@conda-forge-admin, please rerender

**Comment by martinRenou** [comment]
friendly ping @bollwyvl !

**Comment by bollwyvl** [comment]
:laughing:   You can ping all you want, but if I'm asleep, not going to do much!

Since yer here: how about putting out a release of https://github.com/MarketSquare/jupyterlab_robotmode so we can start thinking about getting ready for the nightmare that will be supporting multiple CMs... probably not really possible.

**Comment by martinRenou** [comment]
Thanks!

> so we can start thinking about getting ready for the nightmare that will be supporting multiple CMs

Sounds like a lot of fun 😄 Unfortunately I may not find time to put cycles on this one

**Comment by bollwyvl** [comment]
Yep, just need the `0.4.0` PyPI release for the work that was done last year. On the lab 4 piece, there's some other stuff which may make that transition more pallatable (e.g. treesitter -> lezer).

**Pull request merged**
