### PR TITLE
Release 1.1.12

### PR DESCRIPTION
**Pull request by ibdafna**
Signed-off-by: Itay Dafna <i.b.dafna@gmail.com>

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ibdafna** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Cheers!

**Comment by ibdafna** [comment]
@bollwyvl How long does it usually take until it propagates?

```bash
idafna ~/dev/notebooks  - $ mamba create -n ipydatagrid python=3.9 ipydatagrid=1.1.12 jupyter notebook jupyterlab pandas bqplot numpy -c con
da-forge

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.7.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['python=3.9', 'ipydatagrid=1.1.12', 'jupyter', 'notebook', 'jupyterlab', 'pandas', 'bqplot', 'numpy']

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
Encountered problems while solving.
Problem: nothing provides requested ipydatagrid 1.1.12**
```

**Comment by bollwyvl** [comment]
Often 1-2 hours these days. See _CDN Cloning Status_ on https://conda-forge.org/status/

**Pull request merged**
